
- name: Create developers_groups
  become: yes
  group: name={{developer_groups}} state=present
  delegate_to: "{{server.tags.Name}}"

- name: Create Users
  become: yes
  user:
    name: "{{item.name}}"
    groups: "{{developer_groups}}"
    append: no
    shell: "{{shell}}"
  delegate_to: "{{server.tags.Name}}"
  with_items: "{{add_users}}"

- name: Add keys to account
  become: yes
  authorized_key:
    user: "{{item.name}}"
    key: "{{item.authorized}}"
    exclusive: yes
  delegate_to: "{{server.tags.Name}}"
  with_items: "{{add_users}}"

- name: remove unauthorized user accounts
  user:
    name: "{{item.name}}"
    state: "{{item.state}}"
  delegate_to: "{{server.tags.Name}}"
  with_items: "{{add_users}}"

- name: Add developers_groups group to sudo
  become: yes
  lineinfile: "dest=/etc/sudoers state=present backup=yes regexp='^%{{developer_groups}}' insertafter='^# %wheel' line='%{{developer_groups}} ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  delegate_to: "{{server.tags.Name}}"

- name: reload sshd
  become: yes
  service: name=sshd state=reloaded
  delegate_to: "{{server.tags.Name}}"
