ec2_instances:
  - { hostname: bastion, spec: "{{ bastion_spec }}" }
  - { hostname: ci, spec: "{{ build_server_spec }}" }
  - { hostname: tw_proxy, spec: "{{ tw_proxy_spec }}" }
  - { hostname: public_proxy, spec: "{{ public_proxy_spec }}" }
  - { hostname: product-qa01, spec: "{{ qa_env_spec }}" }

