- name: Allocate a new elastic IP without associating it to anything
  environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  ec2_eip: in_vpc=yes reuse_existing_ip_allowed=yes state=present region="{{aws_region}}"
  register: eip

- name: Fetch All NAT
  environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  shell: "aws ec2 describe-nat-gateways --filter Name=vpc-id,Values={{vpc_id}},Name=state,Values=pending,available"
  register: fetch_nat

- set_fact: nats_to_be_deleted={{fetch_nat.stdout |from_json}}

- name: Delete All NAT
  environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  shell: "aws ec2 delete-nat-gateway --nat-gateway-id {{item.NatGatewayId}}"
  with_items: "{{ nats_to_be_deleted.NatGateways }}"

- name: Create NAT and associate eip
  environment:
      AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
  shell: "aws ec2 create-nat-gateway --region {{aws_region}} --subnet-id {{public_subnet_id}} --allocation-id {{ eip.allocation_id }}"
  register: nat

- set_fact: nat_output={{nat.stdout |from_json}}
