download_folder: /opt
postgres_version: 9.2
postgres_repo_rpm_name: pgdg-centos92-9.2-8.noarch.rpm
postgres_repo_download_url: https://download.postgresql.org/pub/repos/yum/9.2/redhat/rhel-6-x86_64/{{postgres_repo_rpm_name}}
postgres_repo_rpm_location: "{{download_folder}}/{{ postgres_repo_rpm_name}}"
